services:
  web:
    build: .
    container_name: sisdata_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sisdata_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisdata
    volumes:
      - db_data:/var/lib/mysql
      - ./database/sisdata.sql:/docker-entrypoint-initdb.d/sisdata.sql

volumes:
  db_data:
